name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7faa8307d4e94b6bce3228d2c92de5b7cb592119a5388f21176d32edd215f6b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
