name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1df5053404aa9213ae9564e0f0d8a172e0594f13165ea371830b887823612a9c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
