name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a291ac3e7f9ce99c99067fa057d7e8398596e87afe254724665d14a3597d799e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
