name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "47b77342b3b683c4db7806380bb16bbe0266f1e3bd0477303aa5e646cd802170"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
