name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aaa065accd30bfd3655276277a25473c9595e829ce683c6df828002869d0a3b7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
