name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0582d6f5c2b7adce8f5032c6584a06d70ef6c3e5f5295824237aea029487d0d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
