name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "662f4515d4095de0387832ff31586ff0d656a66aea5261699f560874c557833c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
