name = "Shelter From The Storm"
author = "AliceDTRH"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "110e116f664c0edd5acfda79b213804aee7f8f943aa90ae15d00b03e1201095b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
